<?php

namespace MyApp\ParcBundle\Repository;

/**
 * MarqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarqueRepository extends \Doctrine\ORM\EntityRepository
{




    function searchMark($libelle)
    {
        $query= $this->getEntityManager()->createQuery
        ("select m from MyAppParcBundle:Marque m WHERE  m.libelle LIKE  :libelle")
         ->setParameter('libelle','%'.$libelle.'%');
         return
             $query->getResult();
    }













      function searchMarque($libelle){

          $query= $this->getEntityManager()->createQuery("select m from MyAppParcBundle:Marque  m WHERE m.libelle LIKE :libelle");

          $query->setParameter('libelle','%'.$libelle.'%');

          return $query->getResult();
      }
}
